# Generated by Django 4.1.7 on 2023-03-27 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_number', models.IntegerField(max_length=50)),
                ('balance', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='budget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='credit',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=50)),
                ('date_of_credit', models.DateField()),
                ('date_of_paid', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='plan_type',
            fields=[
                ('plan_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('payment', models.IntegerField(max_length=50)),
                ('date_of_issue', models.DateField()),
                ('date_of_exp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='premium',
            fields=[
                ('premium_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.plan_type')),
            ],
        ),
        migrations.CreateModel(
            name='transaction_details',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('amount', models.IntegerField(max_length=50)),
                ('date', models.DateField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.account')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.category')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.IntegerField()),
                ('f_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ph_no', models.IntegerField(max_length=10)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='transaction_details',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.user'),
        ),
        migrations.AddField(
            model_name='premium',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.user'),
        ),
        migrations.AddField(
            model_name='credit',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.user'),
        ),
        migrations.AddField(
            model_name='budget',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.category'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.user'),
        ),
    ]
