# Generated by Django 4.2.2 on 2023-07-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses_Category', '0003_alter_expensescategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensescategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
