# Generated by Django 4.2.2 on 2023-07-06 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Expenses_Category', '0004_alter_expensescategory_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_limit', models.FloatField(blank=True, default=0)),
                ('category_limit', models.FloatField(blank=True, default=0)),
                ('expenses_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Expenses_Category.expensescategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Limit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
