# Generated by Django 4.2.2 on 2023-07-06 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Limit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limit',
            name='currency',
            field=models.CharField(blank=True, default='Rs.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='limit',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
