# Generated by Django 4.2.2 on 2023-07-08 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Expenses_Category', '0004_alter_expensescategory_image'),
        ('Limit', '0002_limit_created_date_limit_currency_limit_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limit',
            name='category_limit',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='expenses_Category',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='limit',
            name='category_limits',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='limit',
            name='expenses_categories',
            field=models.ManyToManyField(blank=True, to='Expenses_Category.expensescategory'),
        ),
        migrations.AlterField(
            model_name='limit',
            name='overall_limit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='limit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to=settings.AUTH_USER_MODEL),
        ),
    ]
