# Generated by Django 4.2.2 on 2023-07-08 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses_Category', '0004_alter_expensescategory_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Limit', '0003_remove_limit_category_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limit',
            name='category_limits',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='expenses_categories',
        ),
        migrations.AddField(
            model_name='limit',
            name='category_limit',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='limit',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limit',
            name='currency',
            field=models.CharField(blank=True, default='Rs.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='limit',
            name='expenses_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Expenses_Category.expensescategory'),
        ),
        migrations.AddField(
            model_name='limit',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='limit',
            name='overall_limit',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='limit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Limit', to=settings.AUTH_USER_MODEL),
        ),
    ]
