# Generated by Django 4.2.2 on 2023-07-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Limit', '0005_remove_limit_currency_alter_limit_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
