# Generated by Django 4.2.2 on 2023-07-12 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('discription', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('payable', 'Payable'), ('receivable', 'Receivable')], max_length=20)),
                ('date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Todo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
