# Generated by Django 4.2.1 on 2023-05-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_myuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='fName',
            new_name='name',
        ),
    ]
