# Generated by Django 4.2.1 on 2023-05-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_fname_myuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='name',
            new_name='fName',
        ),
    ]
