# Generated by Django 4.2.1 on 2023-06-05 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Income_Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_Date', models.DateField(auto_now=True)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('incCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Income_Category.incomecategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
